### ISSUE TITLE
Base gentoo files for sys-apps/file and dev-python/jsonschema are missing.

### ISSUE THREAD

**Issue by adamkruszewski** [tgbugs/tgbugs-overlay#9]
Hi, 
There are two "files" present in the Manifests in the Overlay that are relaying on a symlink to `/usr/portage`.
Not sure exactly when `/usr/portage` stopped being available for a `/var/db/repos/gentoo` location but the result is
the system update with the overlay active was not possible today for me.

The output is:
```
>>> Verifying ebuild manifests

!!! A file listed in the Manifest could not be found: /var/lib/layman/tgbugs-overlay/sys-apps/file/files/file-5.39-portage-sandbox.patch

!!! A file listed in the Manifest could not be found: /var/lib/layman/tgbugs-overlay/dev-python/jsonschema/files/jsonschema-3.2.0-add-webcolors-1.11-compat.patch
```
`/var/lib/layman/tgbugs-overlay/sys-apps/file/files` and `/var/lib/layman/tgbugs-overlay/dev-python/jsonschema/files` points to `/usr/portage` path.

A workaround is just to provide the symlink /usr/portage to the new location, but I guess it might be more useful to change the symlinks in the overlay itself?

I have opened a PR at https://github.com/tgbugs/tgbugs-overlay/pull/8
(but it is a very simple change so you may want to just commit it yourself).

Many thanks,
Adam.

**Comment by tgbugs** [comment]
Unfortunately there isn't an easy way to fix this within the overlay because we need to be able to support both old and new locations of the portage tree. There are a large number of `./files` folders symlinked into `/usr/portage` through this overlay so it doesn't make sense to only switch these two.

The simplest solution is to symlink `/usr/portage` to `/var/db/repos/gentoo` so that the symlinks can resolve. There aren't other good solutions because they all significantly increase the maintenance burden or leave the overlay in a fundamentally broken state when it is first clone and ultimately force everyone to symlink, not just one group (old vs new location).

When the majority of my systems switch over to `/var/db/repos/gentoo` by default I will make the switch here as well, but that is likely to be years away still.

**Comment by adamkruszewski** [comment]
Make sense, I think I just have those two installed and that's why only those two popped up. Thanks!
